#!/usr/bin/env python3
"""Build a file:// compatible folder, standalone HTML, and offline browser ZIP."""
import argparse
import base64
import hashlib
import json
import re
import shutil
import subprocess
import tomllib
import zipfile
from pathlib import Path

root = Path(__file__).resolve().parent.parent
parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument("--skip-compile", action="store_true", help="Reuse previously compiled WASM")
args = parser.parse_args()
generated = root / "target/browser-bindgen"
if not args.skip_compile:
    subprocess.run(["cargo", "build", "--locked", "--release", "--lib", "--no-default-features",
                    "--features", "browser", "--target", "wasm32-unknown-unknown"], cwd=root, check=True)
    subprocess.run(["wasm-bindgen", "--target", "no-modules", "--no-typescript", "--out-dir", str(generated),
                    "--out-name", "recurrence_engine",
                    str(root / "target/wasm32-unknown-unknown/release/recurrence_lab.wasm")], check=True)

worker = (generated / "recurrence_engine.js").read_text()
encoded = base64.b64encode((generated / "recurrence_engine_bg.wasm").read_bytes()).decode()
worker += "\nwasm_bindgen.initSync({ module: Uint8Array.from(atob(" + json.dumps(encoded) + "), c => c.charCodeAt(0)) });\n"
worker += """
self.onmessage = ({data}) => {
  try {
    let result;
    switch (data.operation) {
      case 'catalog': result = wasm_bindgen.browser_catalog(); break;
      case 'generate': result = wasm_bindgen.browser_generate(JSON.stringify(data.payload)); break;
      case 'replay': result = wasm_bindgen.browser_replay(typeof data.payload === 'string' ? data.payload : JSON.stringify(data.payload)); break;
      case 'tex': result = wasm_bindgen.browser_tex(JSON.stringify(data.payload.problem), data.payload.solution); break;
      default: throw new Error('Unknown browser operation');
    }
    self.postMessage({id:data.id, result});
  } catch (error) {
    self.postMessage({id:data.id, error: String(error.message || error)});
  }
};
"""
engine = "// Generated by scripts/build-browser.py; source: src/browser.rs.\nwindow.RECURRENCE_ENGINE_SOURCE = " + json.dumps(worker, ensure_ascii=True).replace("<", "\\u003c") + ";\n"
output = root / "browser"
shutil.copytree(root / "web", output, dirs_exist_ok=True)
(output / "engine.js").write_text(engine)
html = (output / "index.html").read_text()
runtime_tag = '<script defer src="./browser-runtime.js"></script>'
assert runtime_tag in html, "web/index.html must load the browser runtime before app.js"
html = html.replace(runtime_tag, '<script defer src="./engine.js"></script>\n  ' + runtime_tag)
(output / "index.html").write_text(html)

# Inline every stylesheet, font, script and icon; move classic scripts after the
# document so removing `defer` still preserves their initialization order.
def inline_style(match):
    path = output / match.group(1)
    css = path.read_text()
    def inline_font(font_match):
        font_path = path.parent / font_match.group(1).strip('"\'')
        assert font_path.is_file(), font_path
        mime = {".woff2": "font/woff2", ".woff": "font/woff", ".ttf": "font/ttf"}[font_path.suffix]
        data = base64.b64encode(font_path.read_bytes()).decode()
        return "url(data:" + mime + ";base64," + data + ")"
    css = re.sub(r"url\(([^)]+)\)", inline_font, css)
    return "<style>" + css + "</style>"

standalone = re.sub(r'<link rel="stylesheet" href="([^"]+)">', inline_style, html)
standalone = standalone.replace('href="./index.html"', 'href="#"')
icon = "data:image/svg+xml;base64," + base64.b64encode((output / "favicon.svg").read_bytes()).decode()
standalone = standalone.replace('href="./favicon.svg"', 'href="' + icon + '"')
scripts = []
def inline_script(match):
    script = (output / match.group(1)).read_text().replace("</script", "<\\/script")
    scripts.append("<script>\n" + script + "\n</script>")
    return ""
standalone = re.sub(r'<script defer src="([^"]+)"></script>', inline_script, standalone)
license_text = (output / "vendor/KATEX-LICENSE").read_text()
standalone = standalone.replace("</body>", "<!-- Bundled KaTeX license:\n" + license_text + "-->\n" + "\n".join(scripts) + "\n</body>")
(output / "漸化式ラボ.html").write_text(standalone)
usage = "漸化式ラボ.html をブラウザーで開いてください。サーバー・インストール・通信は不要です。\n問題はRust/WebAssemblyで生成し、初期条件と1〜20の漸化式を厳密計算で検査します。\nブラウザーではLeanによる全項証明を実行しません。\nソース: https://github.com/mas256/recurrence-equation-generator\n"
(output / "使い方.txt").write_text(usage)
dist = root / "dist"
dist.mkdir(exist_ok=True)
archive = dist / "recurrence-lab-browser.zip"
with zipfile.ZipFile(archive, "w", zipfile.ZIP_DEFLATED, compresslevel=9) as bundle:
    for name in ("漸化式ラボ.html", "使い方.txt", "vendor/KATEX-LICENSE"):
        bundle.write(output / name, "recurrence-lab/" + Path(name).name)
version = tomllib.loads((root / "Cargo.toml").read_text())["package"]["version"]
manifest = {"version": version, "artifact": archive.name, "bytes": archive.stat().st_size,
            "sha256": hashlib.sha256(archive.read_bytes()).hexdigest(),
            "html_bytes": (output / "漸化式ラボ.html").stat().st_size,
            "wasm_sha256": hashlib.sha256((generated / "recurrence_engine_bg.wasm").read_bytes()).hexdigest()}
(dist / "browser-manifest.json").write_text(json.dumps(manifest, indent=2) + "\n")
print(json.dumps(manifest, indent=2))
